"""add xp level and streak system

Revision ID: d75177274075
Revises: c4f0322c51e7
Create Date: 2026-03-13 06:11:03.765184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd75177274075'
down_revision = 'c4f0322c51e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('xp', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('level', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('streak_current', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('streak_longest', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_activity_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_activity_date')
        batch_op.drop_column('streak_longest')
        batch_op.drop_column('streak_current')
        batch_op.drop_column('level')
        batch_op.drop_column('xp')

    # ### end Alembic commands ###
